<?php

namespace Database\Seeders;

use App\Models\VulnDb;
use App\Models\User;
use Illuminate\Database\Seeder;

class VulnDbSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::where('role', '!=', 'service')->orderBy('id')->get()->keyBy('email');
        $admin = $users['admin@garuda-siber.internal'];
        $staff = $users['user@garuda-siber.internal'];

        $vulns = [
            [
                'cve_id' => 'CVE-2021-44228',
                'name' => 'Log4Shell Remote Code Execution',
                'description' => 'Kerentanan pada pustaka log4j versi 2.x yang memungkinkan pemanggilan JNDI jarak jauh dan berujung eksekusi kode.',
                'severity' => 'critical',
                'cvss_score' => 10.0,
                'category' => 'Injection',
                'affected_systems' => 'Apache Log4j 2.0-beta9 sampai 2.14.1',
                'published_year' => '2021',
                'remediation' => 'Tingkatkan ke log4j 2.17.1 atau lebih baru dan nonaktifkan pencarian JNDI.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2014-0160',
                'name' => 'Heartbleed Memory Disclosure',
                'description' => 'Kegagalan pemeriksaan panjang pada ekstensi TLS OpenSSL yang membocorkan kunci privat dan data sesi dari memori proses.',
                'severity' => 'critical',
                'cvss_score' => 7.5,
                'category' => 'Cryptography',
                'affected_systems' => 'OpenSSL 1.0.1 sampai 1.0.1g',
                'published_year' => '2014',
                'remediation' => 'Tingkatkan OpenSSL, ganti seluruh sertifikat dan kunci privat yang pernah dipakai.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2017-0144',
                'name' => 'EternalBlue SMB Exploitation',
                'description' => 'Kerentanan buffer overflow pada protokol SMBv1 yang digunakan untuk pergerakan lateral dan penyebaran ransomware.',
                'severity' => 'critical',
                'cvss_score' => 8.1,
                'category' => 'Access Control',
                'affected_systems' => 'Windows SMBv1 tanpa patch MS17-010',
                'published_year' => '2017',
                'remediation' => 'Terapkan patch MS17-010 dan matikan SMBv1 pada seluruh host.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2022-22965',
                'name' => 'Spring Framework RCE',
                'description' => 'Kerentanan pada Spring MVC yang dapat dipicu melalui parameter binder untuk menulis berkas di server.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Injection',
                'affected_systems' => 'Spring Framework 5.3.0 sampai 5.3.17',
                'published_year' => '2022',
                'remediation' => 'Tingkatkan ke Spring Framework 5.3.18 atau versi yang lebih baru.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2023-4966',
                'name' => 'Citrix Bleed Session Hijacking',
                'description' => 'Penanganan token sesi yang tidak benar pada appliance Citrix NetScaler yang memungkinkan pencurian sesi aktif.',
                'severity' => 'critical',
                'cvss_score' => 9.4,
                'category' => 'Access Control',
                'affected_systems' => 'Citrix NetScaler ADC dan Gateway yang terdampak',
                'published_year' => '2023',
                'remediation' => 'Terapkan firmware terbaru dan lakukan pencabutan seluruh sesi aktif setelah patch.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2021-41773',
                'name' => 'Apache Path Traversal',
                'description' => 'Normalisasi path yang tidak memadai pada Apache HTTP Server memungkinkan pembacaan berkas di luar document root.',
                'severity' => 'critical',
                'cvss_score' => 7.5,
                'category' => 'Access Control',
                'affected_systems' => 'Apache HTTP Server 2.4.49 dan 2.4.50',
                'published_year' => '2021',
                'remediation' => 'Tingkatkan ke 2.4.51 dan nonaktifkan allowOverride yang tidak diperlukan.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2019-11043',
                'name' => 'PHP-FPM Arbitrary Code Execution',
                'description' => 'Kegagalan validasi data pada PHP-FPM yang dapat memicu eksekusi kode jarak jauh melalui permintaan yang dibuat-buat.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Injection',
                'affected_systems' => 'PHP 7.1 sampai 7.3.11 dengan konfigurasi tertentu',
                'published_year' => '2019',
                'remediation' => 'Tingkatkan PHP ke 7.3.12 atau lebih baru dan batasi fastcgi_split_path_info.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2018-7600',
                'name' => 'Drupalgeddon 2 RCE',
                'description' => 'Kerentanan pada modul Form API Drupal yang memungkinkan administrator situs menjalankan kode arbitrer.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Injection',
                'affected_systems' => 'Drupal 7 dan 8 sebelum rilis patch Juli 2018',
                'published_year' => '2018',
                'remediation' => 'Terapkan Drupalgeddon 2 patch dan audit hak akses administrator.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2020-1472',
                'name' => 'Netlogon Elevation of Privilege',
                'description' => 'Kerentanan pada protokol autentikasi Netlogon yang memungkinkan penyerang menaikkan hak akses menjadi domain admin.',
                'severity' => 'critical',
                'cvss_score' => 10.0,
                'category' => 'Access Control',
                'affected_systems' => 'Windows Server dengan Secure RPC belum dipatch',
                'published_year' => '2020',
                'remediation' => 'Terapkan patch August 2020 dan aktifkan Secure RPC enforcement.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2022-0778',
                'name' => 'OpenSSL Infinite Loop DoS',
                'description' => 'Pemrosesan sertifikat X.509 yang berulang tanpa batas menyebabkan kehabisan sumber daya saat handshake TLS.',
                'severity' => 'high',
                'cvss_score' => 7.5,
                'category' => 'Denial of Service',
                'affected_systems' => 'OpenSSL 1.1.1 sampai 1.1.1n',
                'published_year' => '2022',
                'remediation' => 'Tingkatkan OpenSSL ke 1.1.1n atau versi yang lebih baru.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2023-23397',
                'name' => 'Outlook NTLM Credential Leak',
                'description' => 'Perbedaan perilaku parsing NTLM antara Outlook dan Exchange memungkinkan pencurian kredensial melalui koneksi NTLM.',
                'severity' => 'high',
                'cvss_score' => 9.8,
                'category' => 'Access Control',
                'affected_systems' => 'Microsoft Outlook 2013 sampai 2021',
                'published_year' => '2023',
                'remediation' => 'Terapkan patch keamanan Outlook dan nonaktifkan NTLM pada perimeter.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2021-26855',
                'name' => 'ProxyLogon SSRF Exchange',
                'description' => 'Kerentanan pada Microsoft Exchange Server yang dapat disalahgunakan untuk akses server internal dan eksekusi kode.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Server Side Request Forgery',
                'affected_systems' => 'Microsoft Exchange Server 2013 sampai 2019',
                'published_year' => '2021',
                'remediation' => 'Terapkan patch March 2021 dan gunakan hotfix resmi Microsoft.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2019-19781',
                'name' => 'Citrix Directory Traversal',
                'description' => 'Kerentanan pada Citrix ADC yang memungkinkan penyerang membaca berkas arbitrer dari sistem berkas.',
                'severity' => 'high',
                'cvss_score' => 9.8,
                'category' => 'Access Control',
                'affected_systems' => 'Citrix ADC firmware 13.0 dan 12.1',
                'published_year' => '2019',
                'remediation' => 'Perbarui firmware Citrix dan batasi akses ke antarmuka manajemen.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2021-34527',
                'name' => 'PrintNightmare Spooler Privilege Escalation',
                'description' => 'Layanan Print Spooler dapat dimuat dengan driver arbitrer untuk menjalankan kode sebagai SYSTEM dari host jarak jauh.',
                'severity' => 'critical',
                'cvss_score' => 8.8,
                'category' => 'Access Control',
                'affected_systems' => 'Windows 10 dan Windows Server tanpa patch Juli 2021',
                'published_year' => '2021',
                'remediation' => 'Terapkan patch Juli 2021 dan nonaktifkan Print Spooler pada host yang tidak memakainya.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2020-0796',
                'name' => 'SMBGhost SMBv3 RCE',
                'description' => 'Penanganan parameter pada protokol SMBv3 yang salah menyebabkan eksekusi kode jarak jauh pada Windows.',
                'severity' => 'critical',
                'cvss_score' => 10.0,
                'category' => 'Injection',
                'affected_systems' => 'Windows 10 versi 1903 dan 1909',
                'published_year' => '2020',
                'remediation' => 'Terapkan patch March 2020 dan matikan SMBv1.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2016-5195',
                'name' => 'Dirty COW Race Condition',
                'description' => 'Kondisi balapan pada salinan halaman kernel di Linux yang memungkinkan penulisan ke berkas hak akses root.',
                'severity' => 'high',
                'cvss_score' => 7.8,
                'category' => 'Access Control',
                'affected_systems' => 'Linux kernel 2.6.18 sampai 4.8.3',
                'published_year' => '2016',
                'remediation' => 'Tingkatkan kernel ke 4.9 atau lebih baru.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2023-34362',
                'name' => 'MOVEit Transfer SQL Injection',
                'description' => 'Kerentanan injeksi SQL pada MOVEit Transfer yang digunakan untuk membocorkan data tanpa autentikasi.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Injection',
                'affected_systems' => 'MOVEit Transfer 15.0 dan versi terkait',
                'published_year' => '2023',
                'remediation' => 'Terapkan patch resmi dan rotasi seluruh kredensial yang pernah dipakai.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2018-11776',
                'name' => 'Apache Struts OGNL Injection',
                'description' => 'Penanganan parameter namespace yang salah pada Apache Struts memungkinkan eksekusi kode jarak jauh.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Injection',
                'affected_systems' => 'Apache Struts 2.3 sampai 2.5.16',
                'published_year' => '2018',
                'remediation' => 'Tingkatkan ke Struts 2.5.17 dan audit aturan validasi input.',
                'created_by' => $staff->id,
            ],
            [
                'cve_id' => 'CVE-2021-3712',
                'name' => 'OpenSSL Read Buffer Overrun',
                'description' => 'Pemrosesan input ASN.1 yang salah dapat menumpuk buffer dan memicu eksekusi kode pada kondisi tertentu.',
                'severity' => 'high',
                'cvss_score' => 7.4,
                'category' => 'Memory Safety',
                'affected_systems' => 'OpenSSL 1.1.1 sampai 1.1.1l',
                'published_year' => '2021',
                'remediation' => 'Tingkatkan ke OpenSSL 1.1.1l atau lebih baru.',
                'created_by' => $admin->id,
            ],
            [
                'cve_id' => 'CVE-2014-6271',
                'name' => 'ShellShock Bash',
                'description' => 'Kesalahan parsing variabel lingkungan pada bash memungkinkan penyerang menjalankan perintah melalui header HTTP.',
                'severity' => 'critical',
                'cvss_score' => 9.8,
                'category' => 'Injection',
                'affected_systems' => 'bash sebelum 4.3 patch level 10',
                'published_year' => '2014',
                'remediation' => 'Tingkatkan bash ke 4.3 atau lebih baru dan ganti fungsi CGI yang relevan.',
                'created_by' => $staff->id,
            ],
        ];

        foreach ($vulns as $vuln) {
            VulnDb::create($vuln);
        }
    }
}
